### ISSUE TITLE
地震が来ているのにもかかわらず、通知されない問題

### ISSUE THREAD

**Issue by nirot1r** [neiropw/ep8#38]

**Comment by nirot1r** [comment]
次に事象が確認された場合はきちんとログとって検証する

**Comment by nirot1r** [comment]
```
app[main] : welcome to ep8!
modules.discord[ready] : logged in as ep8#3035!
modules.discord[ready] : starting eq steram...
modules.eq[nhk] : new eq
modules.eq[nhk] : new eq
modules.eq[nhk] : new eq
modules.eq[nhk] : new eq
modules.eq[km] : new eq
modules.eq[km] : new eq report
20180908 20180908231204
lib.generate_map : downloaded base
modules.eq[km] : new eq report
20180908 20180908231210
lib.generate_map : downloaded base
modules.eq[km] : new eq report
20180908 20180908231230
lib.generate_map : downloaded base
modules.eq[km] : new eq report
20180908 20180908231249
lib.generate_map : downloaded base
modules.eq[km] : new eq report
20180908 20180908231258
lib.generate_map : downloaded base
modules.eq[nhk] : new eq
lib.cmd[control] : 変数出力
```

**Comment by nirot1r** [comment]
```
20180908 20180908231204
lib.generate_map : downloaded base
```
この辺で詰んでそう

**Comment by nirot1r** [comment]
http://www.kmoni.bosai.go.jp/new/data/map_img/EstShindoImg/eew/20180908/20180908231204.eew.gif
http://www.kmoni.bosai.go.jp/new/data/map_img/PSWaveImg/eew/20180908/20180908231204.eew.gif
http://www.kmoni.bosai.go.jp/new/data/map_img/RealTimeImg/jma_s/20180908/20180908231204.jma_s.gif

一応データはあるっぽい

**Comment by nirot1r** [comment]
https://github.com/neiropw/ep8/blob/2dfe31b891923096f46c22af85b86a488c562bf1/lib/generate_map.js#L35
部分に
```js
} else {
  console.log(`lib.generate_map : downloaded error ${image.name} (${response.statusCode}) (${image.url})`)
}
```
追加して挙動確認しておく

**Comment by nirot1r** [comment]
```
modules.eq[km] : new eq report
20180909 20180909031321
lib.generate_map : downloaded error rtshindo (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/RealTimeImg/jma_s/${date}/${time}.jma_s.gif)
lib.generate_map : downloaded error estshindo (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/EstShindoImg/eew/${date}/${time}.eew.gif)
lib.generate_map : downloaded error ps (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/PSWaveImg/eew/${date}/${time}.eew.gif)
lib.generate_map : downloaded base
modules.eq[km] : new eq report
20180909 20180909031328
lib.generate_map : downloaded error estshindo (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/EstShindoImg/eew/${date}/${time}.eew.gif)
lib.generate_map : downloaded error ps (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/PSWaveImg/eew/${date}/${time}.eew.gif)
lib.generate_map : downloaded error rtshindo (404) (http://www.kmoni.bosai.go.jp/new/data/map_img/RealTimeImg/jma_s/${date}/${time}.jma_s.gif)
lib.generate_map : downloaded base
```

テンプレートあたりが悪さしてそう

**Comment by nirot1r** [comment]
再現出来たらクローズします

**Comment by nirot1r** [comment]
リアルタイム震度だけ数秒遅れてアップロードされるっぽい。
とりあえず3秒前の情報を持ってくるようにした

**Comment by nirot1r** [comment]
悪化していたのでリベート

**Comment by nirot1r** [comment]
```
const request = require('request')
require('date-utils')

const test = () => {
  const date = new Date()
  const time = date.toFormat('YYYYMMDDHH24MISS')
  request(
    { method: 'GET', url: 'http://www.kmoni.bosai.go.jp/new/data/map_img/RealTimeImg/jma_s/20180910/20180910171215.jma_s.gif', encoding: null },
    (error, response) => {
      console.log(`${time} : ${response.statusCode}`)
    }
  )
}
setInterval(test, 500)
```
のテストコードを作成して実行した結果が
```
PS C:\Users\nirot1r\Documents\07-neiropw\ep8\ep8-discord> node test
20180910171210 : 404
20180910171210 : 404
20180910171211 : 404
20180910171211 : 404
20180910171212 : 404
20180910171212 : 404
20180910171213 : 404
20180910171213 : 404
20180910171214 : 404
20180910171214 : 404
20180910171215 : 404
20180910171215 : 404
20180910171216 : 200
20180910171216 : 200
20180910171217 : 200
20180910171217 : 200
```
で、1秒後に200になってるので、1秒前の情報を持ってくるべきなんだと思う

**Comment by nirot1r** [comment]
```
modules.eq[km] : new eq report
20180910
20180910205126
20180910
20180910205125
lib.generate_map : downloaded estshindo
lib.generate_map : downloaded ps
lib.generate_map : downloaded base
lib.generate_map : downloaded rtshindo
lib.generate_map : composited estshindo + ps
(node:6276) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[0].value: This field is required
    at item.request.gen.end (C:\Users\nirot1r\Documents\07-neiropw\ep8\ep8-discord\node_modules\discord.js\src\client\rest\Reques
tHandlers\Sequential.js:79:15)
    at then (C:\Users\nirot1r\Documents\07-neiropw\ep8\ep8-discord\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
lib.generate_map : composited layer + rtshindo
lib.generate_map : composited base + layer
lib.generate_map : done!
lib.generate_map : unlinked
```

**Comment by nirot1r** [comment]
一回画像系の処理を切った安定版出したほうがいい気がする

**Comment by nirot1r** [comment]
```
modules.eq[km] : new eq report
20180910
20180910235931
{"embed":{"title":"地震速報(高度利用) 第11報","color":16711680,"fields":[{"name":"発生時刻","inline":true},{"name":"震央","value"
:"千葉県南東沖","inline":true},{"name":"深さ","value":"30km","inline":true},{"name":"強さ(M)","value":"M5.2","inline":true},{"nam
e":"予想最大震度","value":"震度4","inline":true}]}}
lib.generate_map : downloaded base
(node:7432) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[0].value: This field is required
    at item.request.gen.end (C:\Users\nirot1r\Documents\07-neiropw\ep8\ep8-discord\node_modules\discord.js\src\client\rest\Reques
tHandlers\Sequential.js:79:15)
    at then (C:\Users\nirot1r\Documents\07-neiropw\ep8\ep8-discord\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
lib.generate_map : downloaded estshindo
lib.generate_map : downloaded ps
lib.generate_map : downloaded acmap
lib.generate_map : composited estshindo + ps
lib.generate_map : composited layer + acmap
lib.generate_map : composited base + layer
lib.generate_map : done!
lib.generate_map : unlinked
```

**Comment by nirot1r** [comment]
関係ないところまでキャメルケースにしてたっぽい

**Comment by nirot1r** [comment]
文字データのみの送信確認。
画像データも添付できるようになったらクローズする。

**Comment by nirot1r** [comment]
無事解決しました。
